version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - rtdbNetwork

  hadoop-spark-pig-hive:
    image: suhothayan/hadoop-spark-pig-hive:2.9.2
    container_name: hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8080:8080"
      - "4040:4040"
    tty: true
    stdin_open: true
    volumes:
      - ../app:/myapp
    networks:
      - rtdbNetwork
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y python3-pip &&
        pip3 install --no-cache-dir kafka-python "

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: ifconfig eth0 | grep 'inet' | awk '{print $2}'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "rtdbTopic:1:1"
    depends_on:
      - zookeeper
    networks:
      - rtdbNetwork


  yolov5:
    image: ultralytics/yolov5
    container_name: yolov5
    ports:
      - "9093:9093"
    volumes:
      - ../app:/myapp
      - ../media:/mymedia
    networks:
      - rtdbNetwork
    ipc: "host"
    stdin_open: true
    tty: true
    command: >
      bash -c "
        pip3 install --no-cache-dir kafka-python "

  cassandra_db:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - rtdbNetwork
    

networks:
  rtdbNetwork:
