version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - rtdbNetwork

  hadoop-spark-pig-hive:
    image: suhothayan/hadoop-spark-pig-hive:2.9.2
    container_name: hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8080:8080"
    tty: true
    stdin_open: true
    networks:
      - rtdbNetwork

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: ifconfig eth0 | grep 'inet' | awk '{print $2}'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "rtdbTopic:1:1"
    depends_on:
      - zookeeper
    networks:
      - rtdbNetwork

  # python:
  #   image: python:3.11
  #   container_name: app
  #   volumes:
  #     - ./python:/python
  #   depends_on:
  #     - kafka
  #   networks:
  #     - rtdbNetwork

  # yolov5:
  #   image: ultralytics/yolov5
  #   container_name: yolov5
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./yolov5:/yolov5  
  #   networks:
  #     - rtdbNetwork
  #   command: python3 app/app.py

networks:
  rtdbNetwork:
